import type { AnswerId, Difficulty, QuizQuestion, SecurityDomain } from "./types";

type QuestionSeed = {
  domain: SecurityDomain;
  concept: string;
  prompts: Record<Difficulty, string>;
  correct: string;
  distractors: [string, string, string];
  why: string;
  mitre?: { id: string; name: string };
};

const seeds: QuestionSeed[] = [
  { domain:"security-risk-management", concept:"Risk treatment", prompts:{green:"What does risk mitigation primarily do?",orange:"A critical service has a likely, high-impact outage risk. Which response best reduces the risk?",red:"A control costs more than the loss it is expected to prevent, but regulation requires it. What is the BEST decision?"}, correct:"Implement controls that reduce likelihood or impact", distractors:["Ignore the risk until an event occurs","Transfer ownership of the business process","Remove the risk from the register"], why:"Mitigation applies safeguards to reduce likelihood or impact. Mandatory obligations also constrain purely financial decisions." },
  { domain:"security-risk-management", concept:"Policy hierarchy", prompts:{green:"Which document states management's high-level security intent?",orange:"Teams implement conflicting password rules. What should governance review FIRST?",red:"A standard conflicts with a newly enacted law. What should the organization do FIRST?"}, correct:"The approved security policy and its governing requirements", distractors:["An individual analyst's runbook","A vendor marketing guide","An informal team convention"], why:"Policies express management direction; standards and procedures must trace to policy and applicable legal obligations." },
  { domain:"security-risk-management", concept:"Business impact", prompts:{green:"What is the main purpose of a business impact analysis?",orange:"Before setting recovery priorities, what information is MOST important?",red:"Two services share infrastructure but have different recovery objectives. What should drive restoration order?"}, correct:"Business impact, dependencies, and recovery objectives", distractors:["The age of each server","The size of each engineering team","The number of security tools deployed"], why:"Recovery priorities follow business impact, dependencies, RTOs, and RPOs—not technical popularity." },
  { domain:"asset-security", concept:"Data classification", prompts:{green:"Why is data classified?",orange:"A new dataset contains customer identifiers and public product data. What should its handling follow?",red:"A derived analytics set can be re-identified when joined with another source. How should it be classified?"}, correct:"According to the highest sensitivity and business impact present", distractors:["According to its file size","As public because some fields are public","According to the storage vendor's default"], why:"Classification reflects sensitivity and impact, including aggregation and re-identification risk." },
  { domain:"asset-security", concept:"Data ownership", prompts:{green:"Who normally decides a business dataset's classification?",orange:"Security and a product team disagree about retention. Who is accountable for the business decision?",red:"A processor wants to reuse customer data for analytics. Who must authorize that new purpose?"}, correct:"The accountable data owner", distractors:["Any database administrator","The newest member of the security team","The hardware manufacturer"], why:"The data owner makes accountable classification and use decisions, advised by security, privacy, and legal teams." },
  { domain:"asset-security", concept:"Secure disposal", prompts:{green:"What is the goal of secure media disposal?",orange:"Encrypted drives are leaving organizational control. What should happen before disposal?",red:"A failed self-encrypting SSD cannot be sanitized normally. What is the BEST action?"}, correct:"Use an approved sanitization or destruction method with evidence", distractors:["Delete the visible files only","Rename the volume","Store it indefinitely without tracking"], why:"Disposal must make recovery infeasible and preserve evidence of custody and destruction appropriate to sensitivity." },
  { domain:"security-architecture-engineering", concept:"Defense in depth", prompts:{green:"What does defense in depth mean?",orange:"A public application already has a WAF. What BEST improves resilience to a WAF bypass?",red:"Which design best limits the blast radius of a single control failure?"}, correct:"Use independent, layered preventive and detective controls", distractors:["Rely on one very strong perimeter control","Duplicate the same password everywhere","Disable logging to reduce complexity"], why:"Independent layers prevent one failed or bypassed control from exposing the entire system." },
  { domain:"security-architecture-engineering", concept:"Key management", prompts:{green:"Why should encryption keys be stored separately from encrypted data?",orange:"An application needs database encryption. Where should production keys be kept?",red:"A master key may have been exposed. What action MOST effectively limits continuing risk?"}, correct:"Use managed, access-controlled key storage and rotate affected keys", distractors:["Commit keys beside source code","Email keys to all administrators","Reuse one permanent key in every environment"], why:"Secure lifecycle management includes separation, least privilege, auditability, rotation, and revocation." },
  { domain:"security-architecture-engineering", concept:"Fail secure", prompts:{green:"What does fail secure mean?",orange:"An authorization service becomes unavailable. How should a sensitive admin function behave?",red:"A safety-critical system cannot simply stop when identity infrastructure fails. What is BEST?"}, correct:"Enter a documented state that preserves security while meeting safety requirements", distractors:["Grant all requests until service returns","Silently skip authorization checks","Expose diagnostic credentials to users"], why:"Failure modes must deny unsafe access while accounting explicitly for availability and human safety constraints." },
  { domain:"communication-network-security", concept:"Segmentation", prompts:{green:"What is a primary benefit of network segmentation?",orange:"A user workstation is compromised. Which control best limits access to production databases?",red:"A flat network supports legacy systems that cannot host agents. What is the BEST compensating design?"}, correct:"Enforce least-privilege paths between separated trust zones", distractors:["Increase internet bandwidth","Use one shared administrator account","Place every device on the same VLAN"], why:"Segmentation and controlled conduits reduce lateral movement and blast radius." },
  { domain:"communication-network-security", concept:"Secure protocols", prompts:{green:"Why is HTTPS preferred over HTTP for sensitive traffic?",orange:"A legacy management protocol sends credentials in cleartext. What should replace it?",red:"TLS is enabled but clients accept any certificate. Which property is missing?"}, correct:"Encrypted transport with authenticated peers and certificate validation", distractors:["A shorter network route","A public DNS record","A larger packet size"], why:"Secure communications require confidentiality, integrity, and meaningful peer authentication—not encryption alone." },
  { domain:"communication-network-security", concept:"Firewall policy", prompts:{green:"What does a firewall rule control?",orange:"A new service needs one inbound port from a partner. What is the BEST rule?",red:"A temporary broad rule was added during an outage. What should happen NEXT?"}, correct:"Allow only required sources, destinations, services, and duration", distractors:["Allow all traffic permanently","Disable firewall logging","Permit the entire partner network without review"], why:"Rules should be least-privilege, documented, logged, time-bound when temporary, and reviewed." },
  { domain:"identity-access-management", concept:"Multi-factor authentication", prompts:{green:"What is the primary purpose of multi-factor authentication?",orange:"Password reuse is suspected for a remote account. Which control most directly reduces takeover risk?",red:"Attackers are successfully approving push-fatigue prompts. What is the BEST improvement?"}, correct:"Require independent, phishing-resistant authentication factors", distractors:["Require two versions of the same password","Hide the login page URL","Extend password expiration indefinitely"], why:"Independent and phishing-resistant factors reduce the value of stolen passwords and resist approval manipulation." },
  { domain:"identity-access-management", concept:"Least privilege", prompts:{green:"What is least privilege?",orange:"A developer needs production access for one incident. What is the BEST approach?",red:"Administrators use standing domain privileges for routine work. What change MOST reduces exposure?"}, correct:"Grant just-in-time, scoped access for the required task", distractors:["Give permanent global administrator rights","Share another administrator's account","Disable audit logging during the task"], why:"Scoped, time-bound, attributable access minimizes standing privilege and supports accountability." },
  { domain:"identity-access-management", concept:"Access reviews", prompts:{green:"Why are access reviews performed?",orange:"An employee transfers departments. What should happen to existing entitlements?",red:"A quarterly review has thousands of rubber-stamped approvals. What is the BEST improvement?"}, correct:"Validate access against current role, risk, and actual need", distractors:["Preserve all historical access","Approve access based only on account age","Remove ownership from business managers"], why:"Reviews must be risk-informed and owned by people who understand current business need." },
  { domain:"security-assessment-testing", concept:"Vulnerability validation", prompts:{green:"What is a vulnerability scan designed to identify?",orange:"A scanner reports a critical issue on an internet service. What should happen FIRST?",red:"A critical CVSS finding is unreachable behind strong controls while a medium finding is exploited publicly. What should be prioritized?"}, correct:"Validate exposure and prioritize using exploitability and business context", distractors:["Patch strictly by scanner row order","Ignore all automated findings","Publish the finding before validation"], why:"Risk-based vulnerability management combines technical severity with reachability, active exploitation, and asset impact." },
  { domain:"security-assessment-testing", concept:"Test independence", prompts:{green:"Why can independent assessors add value?",orange:"A team tests a control it designed and always reports success. What improves assurance?",red:"An audit function reports to the executive responsible for the audited program. What is the key concern?"}, correct:"Objectivity and freedom from conflicts of interest", distractors:["Faster typing during testing","Ownership of the production servers","Elimination of evidence collection"], why:"Appropriate independence increases confidence that scope, evidence, and conclusions are unbiased." },
  { domain:"security-assessment-testing", concept:"Rules of engagement", prompts:{green:"What do penetration-test rules of engagement define?",orange:"A tester discovers a path into an out-of-scope partner system. What should they do?",red:"During an authorized test, exploitation may disrupt a critical service. What is the BEST next step?"}, correct:"Stop that activity and follow the agreed escalation and authorization process", distractors:["Continue because the technique works","Hide the discovery from the sponsor","Delete evidence of the test"], why:"Testing must remain within explicit authorization, safety constraints, communication paths, and stop conditions." },
  { domain:"security-operations", concept:"Context before containment", prompts:{green:"What is the purpose of triage in incident response?",orange:"Failed logins are followed by a success from an unfamiliar location. What should an analyst do FIRST?",red:"A privileged cloud login looks anomalous but supports a critical release. What is the BEST immediate approach?"}, correct:"Correlate identity, device, MFA, and surrounding telemetry before proportionate containment", distractors:["Immediately wipe the user's endpoint","Permanently block the source country","Close the alert because login succeeded"], why:"Fast contextual validation supports proportionate containment and avoids both delay and unnecessary disruption.", mitre:{id:"T1078",name:"Valid Accounts"} },
  { domain:"security-operations", concept:"Evidence preservation", prompts:{green:"Why is chain of custody important?",orange:"A potentially compromised laptop is powered on. What should the responder do?",red:"Volatile evidence may disappear, but collection could alter the system. What is BEST?"}, correct:"Use a documented, authorized collection method that preserves integrity", distractors:["Browse files casually before documenting","Let multiple people share the evidence","Reinstall the operating system immediately"], why:"Forensic handling balances volatility with minimal alteration, repeatability, integrity hashes, and documented custody." },
  { domain:"security-operations", concept:"Ransomware containment", prompts:{green:"What is an immediate goal when ransomware is active?",orange:"EDR shows encryption beginning on one workstation. What should the analyst do FIRST?",red:"Encryption is spreading and a critical server cannot be abruptly powered off. What is BEST?"}, correct:"Isolate affected paths quickly while preserving safe business operations and evidence", distractors:["Pay before confirming scope","Delete all security logs","Wait for every asset to show encryption"], why:"Rapid, targeted isolation limits spread; response should preserve evidence and account for operational safety.", mitre:{id:"T1486",name:"Data Encrypted for Impact"} },
  { domain:"software-development-security", concept:"Threat modeling", prompts:{green:"When is threat modeling most valuable?",orange:"A team is designing a new payment workflow. What should security do before implementation?",red:"A design trusts a signed request but not the business action it authorizes. What should threat modeling examine?"}, correct:"Identify assets, trust boundaries, abuse cases, and mitigations early", distractors:["Wait until after production compromise","Review only code formatting","Treat the network diagram as sufficient"], why:"Early threat modeling finds design-level abuse paths when changes are cheaper and more effective." },
  { domain:"software-development-security", concept:"Software supply chain", prompts:{green:"Why are dependencies inventoried?",orange:"A critical library vulnerability is announced. What should the team do FIRST?",red:"A build dependency is compromised upstream. Which design most limits impact?"}, correct:"Verify usage and provenance, then use controlled, reproducible builds and trusted artifacts", distractors:["Download packages from any mirror","Disable dependency scanning","Assume lockfiles prove publisher integrity"], why:"Inventory, provenance, pinning, verification, and isolated builds reduce supply-chain uncertainty and exposure." },
  { domain:"software-development-security", concept:"Secure code review", prompts:{green:"What is a goal of secure code review?",orange:"A query concatenates untrusted input. What is the BEST remediation?",red:"A parameterized query is safe from injection but exposes another customer's record. What control is missing?"}, correct:"Validate both safe data handling and server-side authorization", distractors:["Rely only on client-side validation","Hide the endpoint name","Log the secret value for debugging"], why:"Secure code must address injection and object-level authorization; one control does not substitute for the other." },
];

const ids: AnswerId[] = ["A", "B", "C", "D"];

const scenarioContexts = [
  "During a routine security review",
  "While onboarding a business-critical service",
  "Following a material change to the environment",
  "During an internal control assessment",
  "While responding to an executive risk concern",
  "As part of a regulated workload review",
  "During a cross-functional security exercise",
];

export const questionBank: QuizQuestion[] = seeds.flatMap((seed, seedIndex) =>
  (["green", "orange", "red"] as Difficulty[]).flatMap((difficulty, difficultyIndex) =>
    scenarioContexts.map((context, variantIndex) => {
    const correctIndex = (seedIndex + difficultyIndex) % 4;
    const choices = [...seed.distractors];
    choices.splice(correctIndex, 0, seed.correct);
    const correctAnswer = ids[correctIndex];
    return {
      id: `${seed.domain}-${seedIndex + 1}-${difficulty}-${variantIndex + 1}`,
      domain: seed.domain,
      difficulty,
      question: `${context}, ${seed.prompts[difficulty].charAt(0).toLowerCase()}${seed.prompts[difficulty].slice(1)}`,
      answers: ids.map((id, index) => ({ id, text: choices[index] })),
      correctAnswer,
      explanation: seed.why,
      answerExplanations: Object.fromEntries(ids.map((id, index) => [id, index === correctIndex ? `This is the best answer. ${seed.why}` : `This option does not best address ${seed.concept.toLowerCase()} in the circumstances given.`])) as Record<AnswerId, string>,
      keyConcept: seed.concept,
      mitreTechnique: seed.mitre,
    };
    }),
  ),
);
